orig_dir_changelogs := ../PKHeX.WinForms/Resources/text/changelog*
dest_dir_changelogs := ../PKHeX.Avalonia/Assets/text

all: move-changelogs

move-changelogs:
	echo "Copy changelog files"
	ls $(orig_dir_changelogs)
	cp $(orig_dir_changelogs) $(dest_dir_changelogs)
